on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  develop_merged:
   runs-on: macos-latest
   
   steps:
    - uses: actions/checkout@v2
    
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: 'unnecessary'
    
    - uses: actions/setup-node@v2
      with:
      node-version: 'lts/*'
    
    - uses: ruby/setup-ruby@v1
      with:
      ruby-version: '3.3'
  
    - run: brew install fastlane

    - uses: jdx/mise-action@v2
      with:
        install: true
    
    - uses: mise install tuist@4.20.0

    - uses: mise use tuist@4.20.0

    - uses: mise exec -- tuist version

    - uses: tuist install -u

    - uses: tuist generate --no-open

    - uses: tuist test
