on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  develop_merged:
   runs-on: macos-latest
   
   steps:
    - uses: actions/checkout@v3
    - uses: jdx/mise-action@v2.1.0
    - uses: ruby/setup-ruby@v1
      with:
      ruby-version: '3.3'

    - name: setup xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
      xcode-version: '16.0'
  
    - run: brew install fastlane

    - name: mise action
      uses: jdx/mise-action@v2.1.0
            
    - name: Install mise
      uses: mise install tuist@4.20.0
      uses: mise use tuist@4.20.0
      uses: mise exec -- tuist version

    - name: install Tuist
      uses: tuist install -u

    - name : verify build success
      uses: tuist generate --no-open
      uses: tuist test
