on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  develop_merged:
   runs-on: macos-latest
   
   steps:
     - uses: actions/checkout@v2
     
     - uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SSH_KEY }}
         known_hosts: 'unnecessary'
     
     - uses: actions/setup-node@v2
       with:
        node-version: 'lts/*'
     
     - uses: actions/setup-ruby@v1
       with:
        ruby-version: '2.6'
    
     - run: brew install fastlane
