on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  develop_merged:
   runs-on: macos-latest
   strategy:
    matrix:
      xcodebuild-scheme: ['MercuryApp']

   steps:
    - uses: actions/checkout@v3
    - uses: jdx/mise-action@v2.1.0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: setup xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
  
    - run: brew install fastlane
            
    - name: Install mise
      run: |
        mise install tuist@4.20.0
        mise use tuist@4.20.0
        mise exec -- tuist version

    - name: Install Tuist
      run: tuist install -u

    - name : Verify build success
      run: |
        tuist generate --no-open
        tuist test
