on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
    types: [closed]
    branches:
      - main
      - develop

jobs:
  develop_merged:
   runs-on: macos-latest
   strategy:
    matrix:
      xcodebuild-scheme: ['MercuryApp']

   steps:
    - uses: actions/checkout@v3
    - uses: jdx/mise-action@v2.1.0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Fetch Ignore Files
      env:
        PAT: ${{secrets.GIT_PRIVATE_KEY}}
      run: |
        git clone https://${PAT}@github.com/naldal/Mercury-ignored
        cp Sensitive.xcconfig ./XCConfigs
        cp .env.default ./fastlane
        cp portal.json ./fastlane

    - name: Setup xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Install Fastlane
    - run: brew install fastlane
            
    - name: Install mise
      run: |
        mise install tuist@4.20.0
        mise use tuist@4.20.0
        mise exec -- tuist version

    - name: Install Tuist
      run: tuist install -u

    - name : Verify build success
      run: |
        tuist generate --no-open
        tuist test
